# Generated by Django 4.2.16 on 2024-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='fallbakc.png', upload_to=''),
        ),
    ]
