# Generated by Django 5.1.2 on 2024-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('Villa', 'Villa'), ('Cottage', 'Cottage'), ('Family House', 'Family House')], default='Cottage', max_length=12)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
