# Generated by Django 5.1.3 on 2024-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Sql DB', 'SQL DB'), ('NO Sql DB', 'NO Sql DB')], default='Cottage', max_length=12),
        ),
    ]
