# Generated by Django 5.1.3 on 2024-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_services', '0002_alter_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Sql-DB', 'SQL-DB'), ('NO-Sql-DB', 'NO-Sql-DB')], default='Storage', max_length=12),
        ),
    ]
