# Generated by Django 5.1.3 on 2024-11-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_services', '0003_alter_house_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Service',
        ),
    ]
